version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - dmxnet
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - dmxnet
networks:
  dmxnet:
    driver: bridge
